name = "Solid Night"
author = "anonym123"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de8c5fb24c4d95f2fd48530acaa2d74789d97ff8b7c730cb3329b5b32022f4de"

[versions]
minecraft = "1.19.1"
quilt = "0.17.2-beta.2"
