name = "Solid Night"
author = "anonym123"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed014a7214333c60463ba924dccf3e18ba6ea009b5850dd8ca5722a825579050"

[versions]
minecraft = "1.19.1"
quilt = "0.17.2-beta.2"
