name = "Solid Night"
author = "anonym123"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7433402f1da725ebf09280370b39a8f27bad4e1dfd51b4f0c9e341bae55d5edc"

[versions]
minecraft = "1.19.1"
quilt = "0.17.2-beta.2"
