name = "Solid Night"
author = "anonym123"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "514ba8563b63e32b000dde86db802c97645a9a8820117c64da6688663389b552"

[versions]
minecraft = "1.19.1"
quilt = "0.17.2-beta.2"
